apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydp1
  name: mydp1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: mydp1
  type: NodePort
